kind: Deployment
apiVersion: apps/v1
metadata:
  name: finance
  namespace: assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: 'ghcr.io/tsundata/bot:v0.0.26'
          imagePullPolicy: Always
          env:
            - name: ETCD_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.address
            - name: ETCD_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.username
            - name: ETCD_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.password
          ports:
            - containerPort: 6005
---
apiVersion: v1
kind: Service
metadata:
  namespace: assistant
  name: bot
spec:
  ports:
    - name: http
      port: 6005
      protocol: TCP
      targetPort: 6005
  selector:
    app: bot
  sessionAffinity: ClientIP
  type: ClusterIP
