kind: Deployment
apiVersion: apps/v1
metadata:
  name: cron
  namespace: assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
        - name: cron
          image: 'ghcr.io/tsundata/cron:v0.0.26'
          imagePullPolicy: Always
          env:
            - name: ETCD_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.address
            - name: ETCD_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.username
            - name: ETCD_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.password
