kind: Deployment
apiVersion: apps/v1
metadata:
  name: cron
  namespace: assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
        - name: cron
          image: 'ghcr.io/tsundata/cron:v0.0.26'
          imagePullPolicy: Always
          env:
            - name: CONSUL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.address
            - name: CONSUL_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.scheme
            - name: CONSUL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.username
            - name: CONSUL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.password
            - name: CONSUL_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.token
