kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
  namespace: assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 'ghcr.io/tsundata/gateway:v0.0.26'
          imagePullPolicy: Always
          env:
            - name: ETCD_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.address
            - name: ETCD_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.username
            - name: ETCD_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.password
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: assistant
  name: gateway
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30005
  selector:
    app: gateway
  type: NodePort
