kind: Deployment
apiVersion: apps/v1
metadata:
  name: middle
  namespace: assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: middle
  template:
    metadata:
      labels:
        app: middle
    spec:
      containers:
        - name: middle
          image: 'ghcr.io/tsundata/middle:v0.0.25'
          imagePullPolicy: Always
          env:
            - name: CONSUL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.address
            - name: CONSUL_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.scheme
            - name: CONSUL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.username
            - name: CONSUL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.password
            - name: CONSUL_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.token
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: assistant
  name: middle
spec:
  ports:
    - name: http
      port: 6002
      protocol: TCP
      targetPort: 6002
  selector:
    app: middle
  sessionAffinity: ClientIP
  type: ClusterIP
