kind: Deployment
apiVersion: apps/v1
metadata:
  name: middle
  namespace: assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: middle
  template:
    metadata:
      labels:
        app: middle
    spec:
      containers:
        - name: middle
          image: 'ghcr.io/tsundata/middle:v0.0.26'
          imagePullPolicy: Always
          env:
            - name: ETCD_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.address
            - name: ETCD_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.username
            - name: ETCD_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.password
          ports:
            - containerPort: 6002
---
apiVersion: v1
kind: Service
metadata:
  namespace: assistant
  name: middle
spec:
  ports:
    - name: http
      port: 6002
      protocol: TCP
      targetPort: 6002
  selector:
    app: middle
  sessionAffinity: ClientIP
  type: ClusterIP
