kind: Deployment
apiVersion: apps/v1
metadata:
  name: nlp
  namespace: assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: nlp
  template:
    metadata:
      labels:
        app: nlp
    spec:
      containers:
        - name: nlp
          image: 'ghcr.io/tsundata/nlp:v0.0.26'
          imagePullPolicy: Always
          env:
            - name: ETCD_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.address
            - name: ETCD_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.username
            - name: ETCD_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.password
          ports:
            - containerPort: 6008
---
apiVersion: v1
kind: Service
metadata:
  namespace: assistant
  name: nlp
spec:
  ports:
    - name: http
      port: 6008
      protocol: TCP
      targetPort: 6008
  selector:
    app: nlp
  sessionAffinity: ClientIP
  type: ClusterIP
