kind: Deployment
apiVersion: apps/v1
metadata:
  name: storage
  namespace: assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: 'ghcr.io/tsundata/storage:v0.0.26'
          imagePullPolicy: Always
          env:
            - name: ETCD_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.address
            - name: ETCD_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.username
            - name: ETCD_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.password
          ports:
            - containerPort: 6009
---
apiVersion: v1
kind: Service
metadata:
  namespace: assistant
  name: storage
spec:
  ports:
    - name: http
      port: 6009
      protocol: TCP
      targetPort: 6009
  selector:
    app: storage
  sessionAffinity: ClientIP
  type: ClusterIP
