kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
  namespace: assistant
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: 'ghcr.io/tsundata/web:v0.0.26'
          imagePullPolicy: Always
          env:
            - name: CONSUL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.address
            - name: CONSUL_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.scheme
            - name: CONSUL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.username
            - name: CONSUL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.password
            - name: CONSUL_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: consul-config
                  key: consul.token
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: assistant
  name: web
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
      targetPort: 7000
      nodePort: 30007
  selector:
    app: web
  type: NodePort
