# the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download

env:
  - CGO_ENABLED=0

builds:
  # app
  - main: ./cmd/cron
    id: "cron"
    binary: "cron"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/gateway
    id: "gateway"
    binary: "gateway"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/message
    id: "message"
    binary: "message"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/middle
    id: "middle"
    binary: "middle"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/spider
    id: "spider"
    binary: "spider"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/subscribe
    id: "subscribe"
    binary: "subscribe"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/workflow
    id: "workflow"
    binary: "workflow"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/web
    id: "web"
    binary: "web"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/task
    id: "task"
    binary: "task"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/storage
    id: "storage"
    binary: "storage"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/worker
    id: "worker"
    binary: "worker"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  # agent
  - main: ./cmd/agent/server
    id: "server-agent"
    binary: "server-agent"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/agent/redis
    id: "redis-agent"
    binary: "redis-agent"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - cron
    image_templates:
      - "tsundata/cron:latest"
      - "tsundata/cron:{{ .Tag }}"
    dockerfile: build/cron/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - gateway
    image_templates:
      - "tsundata/gateway:latest"
      - "tsundata/gateway:{{ .Tag }}"
    dockerfile: build/gateway/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - message
    image_templates:
      - "tsundata/message:latest"
      - "tsundata/message:{{ .Tag }}"
    dockerfile: build/message/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - middle
    image_templates:
      - "tsundata/middle:latest"
      - "tsundata/middle:{{ .Tag }}"
    dockerfile: build/middle/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - spider
    image_templates:
      - "tsundata/spider:latest"
      - "tsundata/spider:{{ .Tag }}"
    dockerfile: build/spider/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - storage
    image_templates:
      - "tsundata/storage:latest"
      - "tsundata/storage:{{ .Tag }}"
    dockerfile: build/storage/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - subscribe
    image_templates:
      - "tsundata/subscribe:latest"
      - "tsundata/subscribe:{{ .Tag }}"
    dockerfile: build/subscribe/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - task
    image_templates:
      - "tsundata/task:latest"
      - "tsundata/task:{{ .Tag }}"
    dockerfile: build/task/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - web
    image_templates:
      - "tsundata/web:latest"
      - "tsundata/web:{{ .Tag }}"
    dockerfile: build/web/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - worker
    image_templates:
      - "tsundata/worker:latest"
      - "tsundata/worker:{{ .Tag }}"
    dockerfile: build/worker/Dockerfile

  - goos: linux
    goarch: amd64
    ids:
      - workflow
    image_templates:
      - "tsundata/workflow:latest"
      - "tsundata/workflow:{{ .Tag }}"
    dockerfile: build/workflow/Dockerfile

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^merge:'
      - '^Merge pull request'
      - '^Merge branch'

env_files:
  github_token: ~/.gh_token

release:
  github:
    owner: tsundata
    name: assistant
  name_template: "{{.Tag}}"
