# the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download

env:
  - CGO_ENABLED=0

builds:
  # app
  - main: ./cmd/id
    id: "id"
    binary: "id"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/chatbot
    id: "chatbot"
    binary: "chatbot"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/cron
    id: "cron"
    binary: "cron"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/gateway
    id: "gateway"
    binary: "gateway"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/message
    id: "message"
    binary: "message"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/middle
    id: "middle"
    binary: "middle"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/spider
    id: "spider"
    binary: "spider"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/workflow
    id: "workflow"
    binary: "workflow"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/web
    id: "web"
    binary: "web"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/task
    id: "task"
    binary: "task"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/storage
    id: "storage"
    binary: "storage"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/user
    id: "user"
    binary: "user"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/bot
    id: "bot"
    binary: "bot"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/nlp
    id: "nlp"
    binary: "nlp"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^test:'
      - '^merge:'
      - '^Merge pull request'
      - '^Merge branch'
      - '^debug:'
      - '^ci:'

env_files:
  github_token: ~/.gh_token

release:
  github:
    owner: tsundata
    name: assistant
  name_template: "{{.Tag}}"
