# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  # app
  - main: ./cmd/cron
    id: "cron"
    binary: "cron"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/gateway
    id: "gateway"
    binary: "gateway"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/message
    id: "message"
    binary: "message"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/middle
    id: "middle"
    binary: "middle"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/spider
    id: "spider"
    binary: "spider"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/subscribe
    id: "subscribe"
    binary: "subscribe"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/workflow
    id: "workflow"
    binary: "workflow"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/web
    id: "web"
    binary: "web"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/task
    id: "task"
    binary: "task"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/storage
    id: "storage"
    binary: "storage"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/worker
    id: "worker"
    binary: "worker"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  # agent
  - main: ./cmd/agent/server
    id: "server-agent"
    binary: "server-agent"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/agent/redis
    id: "redis-agent"
    binary: "redis-agent"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/tsundata/assistant/internal/pkg/version.Version={{ .Version }}
        -X github.com/tsundata/assistant/internal/pkg/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/assistant/internal/pkg/version.BuildTime={{ .Timestamp }}
        -X github.com/tsundata/assistant/internal/pkg/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^merge:'
      - '^Merge pull request'
      - '^Merge branch'
env_files:
  github_token: ~/.gh_token
release:
  github:
    owner: tsundata
    name: assistant
  name_template: "{{.Tag}}"
