global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - /rules/*.yml
scrape_configs:
  - job_name: grafana
    static_configs:
      - targets:
          - "grafana:3000"
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: jaeger
    static_configs:
      - targets:
          - "jaeger-collector:14269"
  - job_name: etcd
    static_configs:
      - targets:
          - "etcd:2379"
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
