version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: assistant
      MYSQL_PASSWORD: 123456
    volumes:
      - ./tmp/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./tmp/redis/data:/data
      - ../configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  influx:
    image: quay.io/influxdb/influxdb:v2.0.3
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=12345678
    volumes:
      - ../configs/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8086:8086"

  jaeger-collector:
    image: jaegertracing/all-in-one:1.22
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

  consul-server1:
    image: consul:1.9.3
    volumes:
      - ./tmp/consul/data1:/data
    command: agent -server -ui -client=0.0.0.0 -node=consul-server1 -bind=0.0.0.0 -datacenter=dc1 -bootstrap-expect=3 -data-dir=/data

  consul-server2:
    image: consul:1.9.3
    volumes:
      - ./tmp/consul/data2:/data
    command: agent -server -client=0.0.0.0 -node=consul-server2 -bind=0.0.0.0 -datacenter=dc1 -bootstrap-expect=3 --retry-join=consul-server1 -data-dir=/data
    depends_on:
      - consul-server1

  consul-server3:
    image: consul:1.9.3
    volumes:
      - ./tmp/consul/data3:/data
    command: agent -server -client=0.0.0.0 -node=consul-server3 -bind=0.0.0.0 -datacenter=dc1 -bootstrap-expect=3 --retry-join=consul-server1 -data-dir=/data
    depends_on:
      - consul-server1

  consul-client:
    image: consul:1.9.3
    volumes:
      - ./tmp/consul/data-client:/data
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: agent -client=0.0.0.0 -node=consul-clinet -bind=0.0.0.0 -datacenter=dc1 -retry-join=consul-server1 -data-dir=/data -ui
    depends_on:
      - consul-server2
      - consul-server3

  gateway:
    image: tsundata/gateway:${APP_VERSION}
    restart: always
    environment:
      CONSUL_ADDRESS: ${CONSUL_ADDRESS}
      CONFIG_NAMESPACE: gateway
    ports:
      - "7000:7000"
