name: Docker

on:
  push:
    tags:
      - v*
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git tag
        run: /usr/bin/git describe --tags >> $GIT_TAG
        env:
          GIT_TAG: v0.0.0

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          install-only: true

      - name: Build
        run: make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push cron
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/cron/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cron:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cron:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cron:${GIT_TAG}

      - name: Build and push gateway
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/gateway/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/gateway:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/gateway:${GIT_TAG}

      - name: Build and push message
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/message/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/message:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/message:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/message:${GIT_TAG}

      - name: Build and push middle
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/middle/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/middle:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/middle:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/middle:${GIT_TAG}

      - name: Build and push spider
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/spider/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spider:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/spider:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/spider:${GIT_TAG}

      - name: Build and push storage
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/storage/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/storage:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/storage:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/storage:${GIT_TAG}

      - name: Build and push subscribe
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/subscribe/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/subscribe:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/subscribe:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/subscribe:${GIT_TAG}

      - name: Build and push task
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/task/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/task:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/task:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/task:${GIT_TAG}

      - name: Build and push web
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/web/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/web:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/web:${GIT_TAG}

      - name: Build and push worker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/worker/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/worker:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/worker:${GIT_TAG}

      - name: Build and push workflow
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: build/workflow/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/workflow:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/workflow:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/workflow:${GIT_TAG}
