name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: assistant
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Get dependencies
        run: go mod download

      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -e 'SHOW DATABASES;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE }} < ./scripts/app.sql
          mysql -e 'use ${{ env.DB_DATABASE }};SHOW TABLES;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
